---
- name: Test Vault integration with Ansible
  hosts: localhost
  connection: local
  gather_facts: no

  pre_tasks:
    - name: Install required packages
      pip:
        name: 
          - hvac
          - requests
        state: present
      become: yes

  vars:
    vault_addr: "http://127.0.0.1:8200"
    vault_token: "hvs.DEHrf26A2FphnKgKm376o0kZ"
    proxmox_source_environment: "dev"
    proxmox_destination_environment: "qua"

  tasks:
    - name: Verify Vault health
      uri:
        url: "{{ vault_addr }}/v1/sys/health"
        method: GET
        status_code: [200, 429, 472, 473, 501, 503]
        validate_certs: no
      register: vault_health
      ignore_errors: yes

    - name: Display Vault health status
      debug:
        var: vault_health

    - name: Retrieve Proxmox source secrets
      community.hashi_vault.vault_kv2_get:
        url: "{{ vault_addr }}"
        token: "{{ vault_token }}"
        engine_mount_point: secret
        path: "proxmox/{{ proxmox_source_environment }}"
      register: source_vault_secrets
      ignore_errors: yes
      when: vault_health is success

    - name: Retrieve Proxmox destination secrets
      community.hashi_vault.vault_kv2_get:
        url: "{{ vault_addr }}"
        token: "{{ vault_token }}"
        engine_mount_point: secret
        path: "proxmox/{{ proxmox_destination_environment }}"
      register: destination_vault_secrets
      ignore_errors: yes
      when: vault_health is success

    - name: Display results
      debug:
        msg:
          - "Vault accessible: {{ vault_health.status == 200 }}"
          - "Source secrets retrieved: {{ source_vault_secrets.data is defined }}"
          - "Destination secrets retrieved: {{ destination_vault_secrets.data is defined }}"
