---
- name: Vérifier et sécuriser l'ADC
  hosts: 10.10.150.50
  vars:
    ansible_user: amal
    ansible_become: yes
    ansible_python_interpreter: /usr/bin/python
  tasks:
    - name: Obtenir la dernière connexion réussie
      command: systemctl status sshd.service
      register: last_login
      changed_when: false

    - name: Obtenir la dernière tentative de connexion échouée
      command: systemctl status sshd.service
      register: failed_login
      changed_when: false

    # ... (autres tâches)

    - name: Afficher les résultats
      debug:
        msg: |
          Dernière connexion réussie : {{ last_login.stdout }}
          Dernière tentative échouée : {{ failed_login.stdout }}
          Statut de l'ADC : {{ "En cours d'exécution" if adc_status.status == "started" else "Arrêté ou problème détecté" }}
          Configuration du pare-feu : {{ firewall_config.stdout }}
          Configuration SSL/TLS : {{ ssl_config.stdout }}
          Configuration des logs : {{ log_config.stdout }}
          Mises à jour de sécurité : {{ security_updates.stdout }}
          Rapport de sécurité final : {{ final_security_check.stdout }}
