---
- name: Vérifier l'installation de Zabbix
  hosts: zabbix_server
  gather_facts: no
  become: yes

  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    ansible_become_password: ro0t@sys
    ansible_user: amal

  tasks:
    - name: Vérifier si le package Zabbix est installé
      package:
        name: zabbix-agent
        state: present
      check_mode: yes
      register: zabbix_installed
      ignore_errors: yes

    - name: Vérifier le nom exact du service Zabbix
      shell: systemctl list-units | grep -i zabbix
      register: service_name
      ignore_errors: yes
      changed_when: false

    - name: Vérifier si le service Zabbix est en cours d'exécution
      systemd:
        name: zabbix-agent
        state: started
      check_mode: yes
      register: zabbix_service
      ignore_errors: yes

    - name: Afficher le résultat
      debug:
        msg:
          - "Zabbix est installé: {{ not zabbix_installed.failed }}"
          - "Le service Zabbix est en cours d'exécution: {{ not zabbix_service.failed }}"
          - "Nom du service trouvé: {{ service_name.stdout_lines | default('Aucun service trouvé') }}"
